#! /usr/bin/env ruby
require 'pg'

@arguments = ARGV

CONNECTION = PG.connect(dbname:"expenses")

def help_content
	puts <<~HELP
		An expense recording system

		Commands:

		add AMOUNT MEMO [DATE] - record a new expense
		clear - delete all expenses
		list - list all expenses
		delete NUMBER - remove expense with id NUMBER
		search QUERY - list expenses with a matching memo field
	HELP
end

def list
	result = CONNECTION.exec("SELECT * FROM expenses ORDER BY created_on ASC;")

	result.each do |tuple|
		columns = [ tuple["id"].rjust(3),
					tuple["created_on"].rjust(10),
					tuple["amount"].rjust(12),
					tuple["memo"] ]
		puts columns.join(" | ")
	end
end


def add_expense(amount, memo)
	abort "You must provide an amount and memo." unless amount && memo
	date = Date.today
	sql = "INSERT INTO expenses (amount, memo, created_on) VALUES (#{amount}, '#{memo}', '#{date}');"
  CONNECTION.exec(sql)
end

case @arguments[0]
when "list" then list
when "add" then add_expense(@arguments[1], @arguments[2])
else help_content
end